### ISSUE TITLE
Get shapefiles for subset locations

### ISSUE THREAD

**Issue by Aariq** [EcosystemEcologyLab/SW_Biomass#19]
I think these are roughly in order of priority:

- [x] Pima Co, AZ https://pimamaps.pima.gov/
- [x] [USFS](https://data.fs.usda.gov/geodata/edw/datasets.php?dsetCategory=boundaries)
   - [x] USFS National Forests
   - [x] National Grasslands 
- [x] California (CARB program) – key cutout = state of CA
- [x] Arizona 
    - [ ] agricultural, urban, natural vegetation.
- [x] NEON sites (all of them, not just #15)]
  - [x] Flight Boundaries
  - [x] Borders
  - [x] Tower locations
- [x] [Ameriflux sites](https://github.com/CharlieDevine/AMF_BADM/blob/main/Code/AMF_BADM.R)
- [ ] [Fluxnet sites](https://fluxnet.org/sites/site-list-and-pages/)

**Comment by davidjpmoore** [comment]
That looks correct.
I would put CA ahead of AZ ag/urban/nature

Dave

Sent from my iPhone

On Feb 12, 2024, at 3:07 PM, Eric R. Scott ***@***.***> wrote:

﻿

External Email

I think these are roughly in order of priority:

  *    Pima Co, AZ https://pimamaps.pima.gov/
  *    USFS<https://data.fs.usda.gov/geodata/edw/datasets.php?dsetCategory=boundaries>
     *    USFS National Forests
     *    National Grasslands
  *    Arizona – agricultural, urban, natural vegetation.
  *    California (CARB program) – key cutout = state of CA
  *    NEON sites (all of them, not just #15<https://github.com/cct-datascience/SW_Biomass/issues/15>)]
  *    Ameriflux sites<https://github.com/CharlieDevine/AMF_BADM/blob/main/Code/AMF_BADM.R>
  *    Fluxnet sites<https://fluxnet.org/sites/site-list-and-pages/>

**Comment by Aariq** [comment]
NEON data including borders, flight boundaries (green), and tower locations (points):
![NEON_data](https://github.com/cct-datascience/SW_Biomass/assets/25404783/4ea96546-9a44-4df6-85b7-d9a21238f077)
