### ISSUE TITLE
Investigate data storage options

### ISSUE THREAD

**Issue by Aariq** [EcosystemEcologyLab/SW_Biomass#32]
Investigate the possibility of using a [STAC catalog](https://stacspec.org/en) hosted on either Cyverse or a lab server to store data and metadata used this project and other related projects.

**Comment by Aariq** [comment]
Would also be good to see if there is a UA s3 bucket storage we can easily use since there are issues with the Jetstream2 object storage #25

**Comment by Aariq** [comment]
https://it.arizona.edu/managed-cloud-services

**Comment by KristinaRiemer** [comment]
Data storage options at UA: https://data.library.arizona.edu/data-management/best-practices/storage-back-ups-security

**Comment by KristinaRiemer** [comment]
I think we as a group have a better idea of what options are available for data storage, including pros and cons, and Dave Moore has also made a choice about this (which was the motivation for doing this investigating).
